In [5]:
b.ndim

2

In [7]:
b.shape

(2, 5)

In [13]:
a=np.arange(5,50,5)
a

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [19]:
np.linspace(5,50,5)

array([ 5.  , 16.25, 27.5 , 38.75, 50.  ])

In [26]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a=np.zeros((3,3),dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [48]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [54]:
a=np.array([[1,2,3],[4,5,6]])
b=a.ravel()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
print(b.shape)

(9,)


In [73]:
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [27]:
import numpy as np
k=np.array([6,7,8,9,0,1,2,3,4,5])
f=np.sort(k)
f


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
k=np.array([6,7,8,9,0,1,2,3,4,5])
m=np.append(k,[11,12,13,14,15])
m
print(m[7])
m[8]=1010101
m

3


array([      6,       7,       8,       9,       0,       1,       2,
             3, 1010101,       5,      11,      12,      13,      14,
            15])

In [43]:
s=np.diag([1,2,3,4,5])
s

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [45]:
m%2==0

array([ True, False,  True, False,  True, False,  True, False, False,
       False, False,  True, False,  True, False])

In [47]:
s%2==0

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [49]:
s*2

array([[ 2,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  6,  0,  0],
       [ 0,  0,  0,  8,  0],
       [ 0,  0,  0,  0, 10]])

In [51]:
s+1

array([[2, 1, 1, 1, 1],
       [1, 3, 1, 1, 1],
       [1, 1, 4, 1, 1],
       [1, 1, 1, 5, 1],
       [1, 1, 1, 1, 6]])

In [53]:
s**2

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 16,  0],
       [ 0,  0,  0,  0, 25]])

In [57]:
z=np.array([1,2,3,4,5])
y=np.array([87,65,56,43,32])
print(z+y)

[88 67 59 47 37]


In [59]:
print(z*y)

[ 87 130 168 172 160]


In [63]:
c=np.matmul(z,y)
c

717

In [89]:
z=np.array([[1,2,3,4,5],[12,1,1,13,12],[2,32,34,4,6],[54,43,65,66,65],[76,87,766,56,43]])
y=np.array([[87,65,56,43,32],[21,22,23,24,25],[43,44,45,54,45],[65,56,67,6,7],[76,76,67,68,54]])
np.matmul(z,y)
z==y

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False]])