In [7]:
import cv2
import numpy as np

In [16]:
img=cv2.imread("C:\\Users\\Asus\\OneDrive\\Desktop\\power shheets\\image_examples\\image.jpg",0)
cv2.imshow("Actor",img)
cv2.waitKey()
cv2.destroyAllWindows()

In [17]:
print(img)

[[37 37 37 ... 35 35 35]
 [38 37 37 ... 35 35 35]
 [36 36 36 ... 35 35 35]
 ...
 [35 36 36 ... 35 35 35]
 [35 35 35 ... 35 35 35]
 [35 35 35 ... 35 35 35]]


In [18]:
type(img)

numpy.ndarray

In [19]:
img.shape

(390, 690)

# Resize Image

In [22]:
img=cv2.imread("C:\\Users\\Asus\\OneDrive\\Desktop\\power shheets\\image_examples\\image.jpg",1)
resized_image=cv2.resize(img,(679,750))
gray=cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)
cv2.imshow("Appu",gray)
cv2.waitKey()
cv2.destroyAllWindows()

# Save image

In [23]:
cv2.imwrite("Appu.jpg",gray)

True

# Face Detection Using HAAR Cascade Classifier

In [43]:
face_classifier=cv2.CascadeClassifier("C:\\Users\\Asus\\OneDrive\\Desktop\\power shheets\\Haarcascades\\haarcascade_frontalface_default.xml")
img=cv2.imread("C:\\Users\\Asus\\OneDrive\\Desktop\\power shheets\\image_examples\\image.jpg",1)
img=cv2.resize(img,(679,750))
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces=face_classifier.detectMultiScale(img,1.5,5)
if faces is ():
    print("No face found")
else:
    for (x,y,l,h) in faces:
        cv2.rectangle(img, (x,y), (x+l,y+h),(255,0,255), 1)

cv2.imshow('Face Detection',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [48]:
face_classifier=cv2.CascadeClassifier("C:\\Users\\Asus\\OneDrive\\Desktop\\power shheets\\Haarcascades\\haarcascade_eye.xml")
img=cv2.imread("C:\\Users\\Asus\\OneDrive\\Desktop\\power shheets\\image_examples\\image.jpg",1)
img=cv2.resize(img,(679,750))
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces=face_classifier.detectMultiScale(img,1.5,5)
if faces is ():
    print("No face found")
else:
    for (x,y,l,h) in faces:
        cv2.rectangle(img, (x,y), (x+l,y+h),(255,0,255), 1)

cv2.imshow('Face Detection',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [1]:
import cv2
video=cv2.VideoCapture(0)
while True:
    num, frame=video.read()
    cv2.imshow('Video',frame)
    if cv2.waitKey(1)==ord('q'):
        break
video.release()
cv2.destroyAllWindows()